### PR TITLE
helper functions for working with feature classes

### LINKED ISSUE #4: Create method to look through yamls
It should have three parameters: feature key name (something like `updates__auto_check`), macos version (something like `10.11`), and the action (only care about enable and disable for now). It will then look through the yaml and return all of the following values that are associated with that feature, action, and macos version:

```
    domain
    key
    action_value:
    sudo:
    global:
```

### PR DESCRIPTION
**Pull request by sylvainsf**
Fixes #4.

### CODE REVIEW

**Comment by kameghamegha** [comment]
Can you please give an example how you intend this to be used? Just call them directly with an example input and print the intended outputs. :)

**Comment by sylvainsf** [comment]
Is this what you had in mind?

```
list_features(SYSTEM_CONFIGS)
=> ["updates__auto_check", "updates__auto_download", "updates__auto_update_restart_required", "updates__auto_update", "login_window__guest_account_login", "login_window__disable_auto_login", "sharing__guest_access_to_afp_shared_folders", "sharing__guest_access_to_smb_shared_folders", "menubar__localization_icon", "firewall__system_firewall_state", "devices__ir_controller"]

list_features(SYSTEM_CONFIGS, 10.11)
=> ["updates__auto_check", "updates__auto_download", "updates__auto_update_restart_required", "updates__auto_update", "login_window__guest_account_login", "login_window__disable_auto_login", "sharing__guest_access_to_afp_shared_folders", "sharing__guest_access_to_smb_shared_folders", "menubar__localization_icon", "firewall__system_firewall_state", "devices__ir_controller"]

list_features(SYSTEM_CONFIGS, 10.12)
=> []

show_feature(SYSTEM_CONFIGS, "login_window__guest_account_login", 10.11, "enable")
=> {:domain=>"/Library/Preferences/com.apple.loginwindow", :key=>"GuestEnabled", :action_value=>{"value"=>1}, :sudo=>false, :global=>false}

```

**Comment by kameghamegha** [comment]
Awesome! Much clearer to me. LGTM. They shouldn't be in recipe.rb but I can move them over to the helpers library when it gets merged. (I create that library in my recent pull request).

**Comment by sylvainsf** [comment]
Yeah I wasn't sure where to put it. Feel free to assign me issues for any other libraries etc

**Comment by kameghamegha** [comment]
LGTM!

**Review by kameghamegha — APPROVED** [review]

**Pull request merged**
